manifest:
  group-filter:
    - +babblesim
  projects:
    - name: nrf_hw_models
      url: https://github.com/tannewt/ext_nRF_hw_models
      revision: 24de78c485dce1a6048f8ae1c69a8d70c93b8cdd
      path: modules/bsim_hw_models/nrf_hw_models
    - name: zephyr
      url: https://github.com/adafruit/zephyr
      revision: 8801b409ec554cfd217c159c00f91280ea1331db
      clone-depth: 100
      import: true
