manifest:
  group-filter:
    - +babblesim
  projects:
    - name: nrf_hw_models
      url: https://github.com/tannewt/ext_nRF_hw_models
      revision: bb351cef9e5ab4d175fe3cb7c4d6761d837bac20
      path: modules/bsim_hw_models/nrf_hw_models
    - name: zephyr
      url: https://github.com/adafruit/zephyr
      revision: 3c5a3a72daa3ca6462cd8bc9c8c7c6a41fbf3b2e
      clone-depth: 100
      import: true
